presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: op1st/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/pre-commit:v0.17.0
          command:
            - "prow-job-precommit"
